### ISSUE TITLE
ImportError with upgrade to NetBox 3.5.0

### ISSUE THREAD

**Issue by julianstolp** [jasonyates/netbox-documents#29]
As described in Issue [#12246](https://github.com/netbox-community/netbox/issues/12246) the `utilities` app was reorganized.

Import moved from
`from utilities.forms import TagFilterField`
to
`from utilities.forms.fields import TagFilterField`

### Error

File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_documents/forms.py", line 5, in <module>
    from utilities.forms import TagFilterField, CommentField, DynamicModelChoiceField
### Full Traceback

```
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 97, in handle
    self.check(databases=[database])
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/urls.py", line 8, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox/netbox/extras/plugins/urls.py", line 31, in <module>
    urlpatterns = import_string(f"{plugin_path}.urls.urlpatterns")
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_documents/urls.py", line 2, in <module>
    from . import models, views
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_documents/views.py", line 2, in <module>
    from . import forms, models, tables, filtersets
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_documents/forms.py", line 5, in <module>
    from utilities.forms import TagFilterField, CommentField, DynamicModelChoiceField
ImportError: cannot import name 'TagFilterField' from 'utilities.forms' (/opt/netbox/netbox/utilities/forms/__init__.py)
```

**Comment by Trusthier** [comment]
same error my side ! it's a great plugin, I can't wait to have an update for V3.5 :)
the same error for [netbox-topology-views](https://github.com/mattieserver/netbox-topology-views)

**Comment by Trusthier** [comment]
Nothing urgent I'm staying in 3.4.9, your plugin is more than necessary. Thanks for the feedback and the work!

**Comment by Trusthier** [comment]
The import has changed for v3.5
from utilities.forms to utilities.forms.fields

**Comment by jasonyates** [comment]
I have pushed a new version 0.6.0 that adds support for Netbox 3.5
